FORMAT: 1A
HOST: http://www.google.com

# Boyard
Notes API is a *short texts saving* service similar to its physical paper presence on your table.

# Group Notes
Notes related resources of the **Notes API**

## Notes Collection [/notes]
### Info about all Notes [HEAD]
+ Response 200

    + Headers
    
            X-Notes-Count: 2

### List all Notes [GET]
+ Response 200 (application/json)

        [{
          "id": 1, "title": "Jogging in park"
        }, {
          "id": 2, "title": "Pick-up posters from post-office"
        }]

### Create a Note [POST]
+ Request (application/json)

        { "title": "Buy cheese and bread for breakfast." }

+ Response 201 (application/json)

        { "id": 3, "title": "Buy cheese and bread for breakfast." }

+ Request (text/xml)

        <a><note title="Buy cheese and bread for breakfast." /></a>

+ Response 201 (text/xml)

        <a><note id="3" title="Buy cheese and bread for breakfast." /></a>

## Note [/notes/{id}/{?since}]
A single Note object with all its details

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Note to perform action with. Has example value.
    + since (optional, string) ... From time in format `YYYY-MM-DD`

### Retrieve a Note [GET]
+ Response 200 (application/json)

    + Header

            X-My-Header: The Value

    + Body

            { "id": 2, "title": "Pick-up posters from post-office" }

### Remove a Note [DELETE]
+ Response 204

## Tool [/tool/{id}]

### Check the tools [GET]

+ Request

    + Header
    
            X-Custom-Variant: 1

+ Response 200 (text/plain)

        Body-response for Variant 1

+ Request

    + Header
    
            X-Custom-Variant: 2

+ Response 200 (text/plain)

        Body-response for Variant 2

+ Request

    + Header
    
            X-Custom-Variant: 3

+ Response 200 (text/plain)

        Body-response for Variant 3
